#############################################################################
# Makefile for building: dns-setup
# Generated by qmake (3.0) (Qt 5.5.0)
# Project:  dns-setup.pro
# Template: app
# Command: /opt/qt5/5.5/gcc_64/bin/qmake -o Makefile dns-setup.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DBUILDTIME=\"15:35:50\" -DBUILDDATE=\"2017-03-25\" -DQT_NO_DEBUG -DQT_HELP_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++1y -Wno-unused-parameter -Wno-unused-variable -Wno-unused-local-typedefs -Wno-unused-but-set-variable -Wno-write-strings -Wno-switch -Wno-extra -Wno-reorder -Wno-multichar -Wno-sign-compare -Wunused-function -Woverloaded-virtual -fpermissive -ftemplate-depth=516 -frtti -fexceptions -I/usr/local/include -I/usr/local/include/boost -I/home/jens/Projekte/dns-setup. -I/home/jens/Projekte/dns-setup/src -I/home/jens/Projekte/dns-setup/src/inc -D__BYTE_ORDER=__LITTLE_ENDIAN -DQT_DEPRECATED -DQT_DISABLE_DEPRECATED_BEFORE -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/include -I/home/jens/Projekte/dns-setup/.uic -Isrc -I/home/jens/Projekte/dns-setup/src/inc -I/usr/include -I/opt/qt5/5.5/gcc_64/include -I/opt/qt5/5.5/gcc_64/include/QtHelp -I/opt/qt5/5.5/gcc_64/include/QtWidgets -I/opt/qt5/5.5/gcc_64/include/QtGui -I/opt/qt5/5.5/gcc_64/include/QtNetwork -I/opt/qt5/5.5/gcc_64/include/QtCore -I.moc -I/opt/qt5/5.5/gcc_64/mkspecs/linux-g++
QMAKE         = /opt/qt5/5.5/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = dns-setup1.0.0
DISTDIR = /home/jens/Projekte/dns-setup/.obj/dns-setup1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/Qt5/5.5/gcc_64 -Wl,-rpath,/opt/Qt5/5.5/gcc_64/lib -Wl,-rpath-link,/opt/qt5/5.5/gcc_64/lib
LIBS          = $(SUBLIBS) -L/usr/local/lib64 -lstdc++ -L/opt/qt5/5.5/gcc_64/lib -lQt5Help -L/usr/lib64 -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = .obj/

####### Files

SOURCES       = src/main.cc \
		src/mainwindow.cc \
		src/label.cc \
		src/thread.cc \
		src/rmiserver.cc .moc/moc_mainwindow.cpp \
		.moc/moc_label.cpp \
		.moc/moc_thread.cpp \
		.moc/moc_rmiserver.cpp
OBJECTS       = .obj/main.o \
		.obj/mainwindow.o \
		.obj/label.o \
		.obj/thread.o \
		.obj/rmiserver.o \
		.obj/moc_mainwindow.o \
		.obj/moc_label.o \
		.obj/moc_thread.o \
		.obj/moc_rmiserver.o
DIST          = app.ini \
		/opt/qt5/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/common/unix.conf \
		/opt/qt5/5.5/gcc_64/mkspecs/common/linux.conf \
		/opt/qt5/5.5/gcc_64/mkspecs/common/sanitize.conf \
		/opt/qt5/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/qt5/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/qt5/5.5/gcc_64/mkspecs/common/g++-base.conf \
		/opt/qt5/5.5/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/qt5/5.5/gcc_64/mkspecs/qconfig.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/qt_config.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/spec_post.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/default_pre.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/default_post.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/warn_on.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/qt.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/resources.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/moc.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/uic.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/exceptions.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/yacc.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/lex.prf \
		dns-setup.pro src/mainwindow.h \
		src/label.h \
		src/thread.h \
		src/rmiserver.h src/main.cc \
		src/mainwindow.cc \
		src/label.cc \
		src/thread.cc \
		src/rmiserver.cc
QMAKE_TARGET  = dns-setup
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = dns-setup


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: dns-setup.pro /opt/qt5/5.5/gcc_64/mkspecs/linux-g++/qmake.conf /opt/qt5/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/common/unix.conf \
		/opt/qt5/5.5/gcc_64/mkspecs/common/linux.conf \
		/opt/qt5/5.5/gcc_64/mkspecs/common/sanitize.conf \
		/opt/qt5/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/qt5/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/qt5/5.5/gcc_64/mkspecs/common/g++-base.conf \
		/opt/qt5/5.5/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/qt5/5.5/gcc_64/mkspecs/qconfig.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt5/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/qt_config.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/spec_post.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/default_pre.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/default_post.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/warn_on.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/qt.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/resources.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/moc.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/uic.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/exceptions.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/yacc.prf \
		/opt/qt5/5.5/gcc_64/mkspecs/features/lex.prf \
		dns-setup.pro \
		/opt/qt5/5.5/gcc_64/lib/libQt5Help.prl \
		/opt/qt5/5.5/gcc_64/lib/libQt5Widgets.prl \
		/opt/qt5/5.5/gcc_64/lib/libQt5Gui.prl \
		/opt/qt5/5.5/gcc_64/lib/libQt5Network.prl \
		/opt/qt5/5.5/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile dns-setup.pro
/opt/qt5/5.5/gcc_64/mkspecs/features/spec_pre.prf:
/opt/qt5/5.5/gcc_64/mkspecs/common/unix.conf:
/opt/qt5/5.5/gcc_64/mkspecs/common/linux.conf:
/opt/qt5/5.5/gcc_64/mkspecs/common/sanitize.conf:
/opt/qt5/5.5/gcc_64/mkspecs/common/gcc-base.conf:
/opt/qt5/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/qt5/5.5/gcc_64/mkspecs/common/g++-base.conf:
/opt/qt5/5.5/gcc_64/mkspecs/common/g++-unix.conf:
/opt/qt5/5.5/gcc_64/mkspecs/qconfig.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/qt5/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/qt5/5.5/gcc_64/mkspecs/features/qt_functions.prf:
/opt/qt5/5.5/gcc_64/mkspecs/features/qt_config.prf:
/opt/qt5/5.5/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/qt5/5.5/gcc_64/mkspecs/features/spec_post.prf:
/opt/qt5/5.5/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/qt5/5.5/gcc_64/mkspecs/features/default_pre.prf:
/opt/qt5/5.5/gcc_64/mkspecs/features/resolve_config.prf:
/opt/qt5/5.5/gcc_64/mkspecs/features/default_post.prf:
/opt/qt5/5.5/gcc_64/mkspecs/features/warn_on.prf:
/opt/qt5/5.5/gcc_64/mkspecs/features/qt.prf:
/opt/qt5/5.5/gcc_64/mkspecs/features/resources.prf:
/opt/qt5/5.5/gcc_64/mkspecs/features/moc.prf:
/opt/qt5/5.5/gcc_64/mkspecs/features/unix/opengl.prf:
/opt/qt5/5.5/gcc_64/mkspecs/features/uic.prf:
/opt/qt5/5.5/gcc_64/mkspecs/features/unix/thread.prf:
/opt/qt5/5.5/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/qt5/5.5/gcc_64/mkspecs/features/exceptions.prf:
/opt/qt5/5.5/gcc_64/mkspecs/features/yacc.prf:
/opt/qt5/5.5/gcc_64/mkspecs/features/lex.prf:
dns-setup.pro:
/opt/qt5/5.5/gcc_64/lib/libQt5Help.prl:
/opt/qt5/5.5/gcc_64/lib/libQt5Widgets.prl:
/opt/qt5/5.5/gcc_64/lib/libQt5Gui.prl:
/opt/qt5/5.5/gcc_64/lib/libQt5Network.prl:
/opt/qt5/5.5/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile dns-setup.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/mainwindow.h src/label.h src/thread.h src/rmiserver.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cc src/mainwindow.cc src/label.cc src/thread.cc src/rmiserver.cc $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: .moc/moc_mainwindow.cpp .moc/moc_label.cpp .moc/moc_thread.cpp .moc/moc_rmiserver.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/moc_mainwindow.cpp .moc/moc_label.cpp .moc/moc_thread.cpp .moc/moc_rmiserver.cpp
.moc/moc_mainwindow.cpp: /opt/qt5/5.5/gcc_64/include/QtWidgets/QApplication \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qapplication.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qarraydata.h \
		/usr/include/string.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/xlocale.h \
		/usr/include/stdlib.h \
		/usr/include/alloca.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qiterator.h \
		/usr/include/limits.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qeventloop.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsize.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qcursor.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmargins.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qrect.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpalette.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qcolor.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qrgb.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qbrush.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qregion.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qline.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtransform.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qimage.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qfont.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qevent.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlocale.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/gconv.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qurl.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qfile.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qguiapplication.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qinputmethod.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QWidget \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QLineEdit \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qlineedit.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qframe.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtextcursor.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtextformat.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpen.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtextoption.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QLabel \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qlabel.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QGroupBox \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qgroupbox.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QMainWindow \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qicon.h \
		src/rmiserver.h \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/QTcpServer \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/qtcpserver.h \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/qabstractsocket.h \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/qhostaddress.h \
		src/mainwindow.h
	/opt/qt5/5.5/gcc_64/bin/moc $(DEFINES) -I/opt/qt5/5.5/gcc_64/mkspecs/linux-g++ -I/home/jens/Projekte/dns-setup -I/usr/local/include -I/home/jens/Projekte/dns-setup/.uic -I/home/jens/Projekte/dns-setup/src -I/home/jens/Projekte/dns-setup/src/inc -I/usr/include -I/opt/qt5/5.5/gcc_64/include -I/opt/qt5/5.5/gcc_64/include/QtHelp -I/opt/qt5/5.5/gcc_64/include/QtWidgets -I/opt/qt5/5.5/gcc_64/include/QtGui -I/opt/qt5/5.5/gcc_64/include/QtNetwork -I/opt/qt5/5.5/gcc_64/include/QtCore src/mainwindow.h -o .moc/moc_mainwindow.cpp

.moc/moc_label.cpp: /opt/qt5/5.5/gcc_64/include/QtCore/QString \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qarraydata.h \
		/usr/include/string.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/xlocale.h \
		/usr/include/stdlib.h \
		/usr/include/alloca.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QLabel \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qlabel.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qframe.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qiterator.h \
		/usr/include/limits.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmargins.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qrect.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsize.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpalette.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qcolor.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qrgb.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qbrush.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qregion.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qline.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtransform.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qimage.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qfont.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qcursor.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qevent.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlocale.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/gconv.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qurl.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qfile.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/QMouseEvent \
		src/label.h
	/opt/qt5/5.5/gcc_64/bin/moc $(DEFINES) -I/opt/qt5/5.5/gcc_64/mkspecs/linux-g++ -I/home/jens/Projekte/dns-setup -I/usr/local/include -I/home/jens/Projekte/dns-setup/.uic -I/home/jens/Projekte/dns-setup/src -I/home/jens/Projekte/dns-setup/src/inc -I/usr/include -I/opt/qt5/5.5/gcc_64/include -I/opt/qt5/5.5/gcc_64/include/QtHelp -I/opt/qt5/5.5/gcc_64/include/QtWidgets -I/opt/qt5/5.5/gcc_64/include/QtGui -I/opt/qt5/5.5/gcc_64/include/QtNetwork -I/opt/qt5/5.5/gcc_64/include/QtCore src/label.h -o .moc/moc_label.cpp

.moc/moc_thread.cpp: /opt/qt5/5.5/gcc_64/include/QtCore/QThread \
		/opt/qt5/5.5/gcc_64/include/QtCore/qthread.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qarraydata.h \
		/usr/include/string.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/xlocale.h \
		/usr/include/stdlib.h \
		/usr/include/alloca.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qiterator.h \
		/usr/include/limits.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/QTcpSocket \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/qtcpsocket.h \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/qabstractsocket.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlocale.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qshareddata.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/gconv.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		src/thread.h
	/opt/qt5/5.5/gcc_64/bin/moc $(DEFINES) -I/opt/qt5/5.5/gcc_64/mkspecs/linux-g++ -I/home/jens/Projekte/dns-setup -I/usr/local/include -I/home/jens/Projekte/dns-setup/.uic -I/home/jens/Projekte/dns-setup/src -I/home/jens/Projekte/dns-setup/src/inc -I/usr/include -I/opt/qt5/5.5/gcc_64/include -I/opt/qt5/5.5/gcc_64/include/QtHelp -I/opt/qt5/5.5/gcc_64/include/QtWidgets -I/opt/qt5/5.5/gcc_64/include/QtGui -I/opt/qt5/5.5/gcc_64/include/QtNetwork -I/opt/qt5/5.5/gcc_64/include/QtCore src/thread.h -o .moc/moc_thread.cpp

.moc/moc_rmiserver.cpp: /opt/qt5/5.5/gcc_64/include/QtNetwork/QTcpServer \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/qtcpserver.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qarraydata.h \
		/usr/include/string.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/xlocale.h \
		/usr/include/stdlib.h \
		/usr/include/alloca.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qiterator.h \
		/usr/include/limits.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/qabstractsocket.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlocale.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qshareddata.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/gconv.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/qhostaddress.h \
		src/rmiserver.h
	/opt/qt5/5.5/gcc_64/bin/moc $(DEFINES) -I/opt/qt5/5.5/gcc_64/mkspecs/linux-g++ -I/home/jens/Projekte/dns-setup -I/usr/local/include -I/home/jens/Projekte/dns-setup/.uic -I/home/jens/Projekte/dns-setup/src -I/home/jens/Projekte/dns-setup/src/inc -I/usr/include -I/opt/qt5/5.5/gcc_64/include -I/opt/qt5/5.5/gcc_64/include/QtHelp -I/opt/qt5/5.5/gcc_64/include/QtWidgets -I/opt/qt5/5.5/gcc_64/include/QtGui -I/opt/qt5/5.5/gcc_64/include/QtNetwork -I/opt/qt5/5.5/gcc_64/include/QtCore src/rmiserver.h -o .moc/moc_rmiserver.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

.obj/main.o: src/main.cc /opt/qt5/5.5/gcc_64/include/QtWidgets/QApplication \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qapplication.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qarraydata.h \
		/usr/include/string.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/xlocale.h \
		/usr/include/stdlib.h \
		/usr/include/alloca.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qiterator.h \
		/usr/include/limits.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qeventloop.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsize.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qcursor.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmargins.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qrect.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpalette.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qcolor.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qrgb.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qbrush.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qregion.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qline.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtransform.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qimage.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qfont.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qevent.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlocale.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/gconv.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qurl.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qfile.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qguiapplication.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qinputmethod.h \
		src/mainwindow.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QWidget \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QLineEdit \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qlineedit.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qframe.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtextcursor.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtextformat.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpen.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtextoption.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QLabel \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qlabel.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QGroupBox \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qgroupbox.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QMainWindow \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qicon.h \
		src/rmiserver.h \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/QTcpServer \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/qtcpserver.h \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/qabstractsocket.h \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/qhostaddress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o src/main.cc

.obj/mainwindow.o: src/mainwindow.cc /opt/qt5/5.5/gcc_64/include/QtWidgets/QApplication \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qapplication.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qarraydata.h \
		/usr/include/string.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/xlocale.h \
		/usr/include/stdlib.h \
		/usr/include/alloca.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qiterator.h \
		/usr/include/limits.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qeventloop.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsize.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qcursor.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmargins.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qrect.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpalette.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qcolor.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qrgb.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qbrush.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qregion.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qline.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtransform.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qimage.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qfont.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qevent.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlocale.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/gconv.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qurl.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qfile.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qguiapplication.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qinputmethod.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QWidget \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QMenuBar \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qmenubar.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qmenu.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qicon.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qaction.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qactiongroup.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QAction \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QGroupBox \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qgroupbox.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qframe.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QHBoxLayout \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qboxlayout.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qlayout.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qlayoutitem.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qgridlayout.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QLabel \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qlabel.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/QPainter \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpainter.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtextoption.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpen.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QPushButton \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qpushbutton.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qabstractbutton.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/QSettings \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsettings.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QStatusBar \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qstatusbar.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QMessageBox \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qmessagebox.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qdialog.h \
		src/label.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/QString \
		/opt/qt5/5.5/gcc_64/include/QtGui/QMouseEvent \
		src/mainwindow.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QLineEdit \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qlineedit.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtextcursor.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtextformat.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QMainWindow \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qtabwidget.h \
		src/rmiserver.h \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/QTcpServer \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/qtcpserver.h \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/qabstractsocket.h \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/qhostaddress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/mainwindow.o src/mainwindow.cc

.obj/label.o: src/label.cc src/mainwindow.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QApplication \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qapplication.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qarraydata.h \
		/usr/include/string.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/xlocale.h \
		/usr/include/stdlib.h \
		/usr/include/alloca.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qiterator.h \
		/usr/include/limits.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qeventloop.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsize.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qcursor.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmargins.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qrect.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpalette.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qcolor.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qrgb.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qbrush.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qregion.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qline.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtransform.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qimage.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qfont.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qevent.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlocale.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/gconv.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qurl.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qfile.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qguiapplication.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qinputmethod.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QWidget \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QLineEdit \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qlineedit.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qframe.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtextcursor.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtextformat.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpen.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtextoption.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QLabel \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qlabel.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QGroupBox \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qgroupbox.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QMainWindow \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qicon.h \
		src/rmiserver.h \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/QTcpServer \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/qtcpserver.h \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/qabstractsocket.h \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/qhostaddress.h \
		src/label.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/QString \
		/opt/qt5/5.5/gcc_64/include/QtGui/QMouseEvent
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/label.o src/label.cc

.obj/thread.o: src/thread.cc src/thread.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/QThread \
		/opt/qt5/5.5/gcc_64/include/QtCore/qthread.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qarraydata.h \
		/usr/include/string.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/xlocale.h \
		/usr/include/stdlib.h \
		/usr/include/alloca.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qiterator.h \
		/usr/include/limits.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/QTcpSocket \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/qtcpsocket.h \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/qabstractsocket.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlocale.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qshareddata.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/gconv.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcontiguouscache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/thread.o src/thread.cc

.obj/rmiserver.o: src/rmiserver.cc /opt/qt5/5.5/gcc_64/include/QtCore/QThread \
		/opt/qt5/5.5/gcc_64/include/QtCore/qthread.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qarraydata.h \
		/usr/include/string.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/xlocale.h \
		/usr/include/stdlib.h \
		/usr/include/alloca.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qiterator.h \
		/usr/include/limits.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QMessageBox \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qmessagebox.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qdialog.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmargins.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qrect.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsize.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpalette.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qcolor.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qrgb.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qbrush.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qregion.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qline.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtransform.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qimage.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qfont.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qcursor.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qevent.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qlocale.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/gconv.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qset.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qurl.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qfile.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QLabel \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qlabel.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qframe.h \
		src/mainwindow.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QApplication \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qapplication.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/qt5/5.5/gcc_64/include/QtCore/qeventloop.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qguiapplication.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qinputmethod.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QWidget \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QLineEdit \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qlineedit.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtextcursor.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtextformat.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qpen.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qtextoption.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QGroupBox \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qgroupbox.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/QMainWindow \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/qt5/5.5/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/qt5/5.5/gcc_64/include/QtGui/qicon.h \
		src/rmiserver.h \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/QTcpServer \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/qtcpserver.h \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/qabstractsocket.h \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/qhostaddress.h \
		src/thread.h \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/QTcpSocket \
		/opt/qt5/5.5/gcc_64/include/QtNetwork/qtcpsocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/rmiserver.o src/rmiserver.cc

.obj/moc_mainwindow.o: .moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_mainwindow.o .moc/moc_mainwindow.cpp

.obj/moc_label.o: .moc/moc_label.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_label.o .moc/moc_label.cpp

.obj/moc_thread.o: .moc/moc_thread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_thread.o .moc/moc_thread.cpp

.obj/moc_rmiserver.o: .moc/moc_rmiserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_rmiserver.o .moc/moc_rmiserver.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

